import { athleteDailyFields } from '@/forms/schemas/athleteDaily'
import { athleteOnboardingFields } from '@/forms/schemas/athleteOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const athleteOnboardingFlow: FormFlowDefinition = {
  id: 'athlete-onboarding-fast-start',
  version: '2026.04.fast-start-v2',
  userType: 'athlete',
  kind: 'onboarding',
  title: 'Athlete Setup',
  description: 'Eight quick questions get you to the dashboard. We learn the rest from your check-ins.',
  completionTargetSeconds: 75,
  fields: athleteOnboardingFields,
  steps: [
    {
      id: 'sport',
      title: 'Your sport',
      goal: 'Pick the primary sport so the system can infer baseline demands.',
      fieldIds: ['primarySport'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'cards',
    },
    {
      id: 'position',
      title: 'Role or event',
      goal: 'Capture the role or event that shapes training focus.',
      fieldIds: ['position'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 6,
      interactionPattern: 'cards',
      helperCopy: 'The options change based on the sport you picked.',
    },
    {
      id: 'level',
      title: 'Level / seriousness',
      goal: 'Calibrate training density and intensity without asking for hours.',
      fieldIds: ['playingLevel'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'chips',
    },
    {
      id: 'dob',
      title: 'Date of birth',
      goal: 'Single DOB drives age, recovery curves, and consent rules.',
      fieldIds: ['dateOfBirth'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'date picker',
    },
    {
      id: 'sex',
      title: 'Sex assigned at birth',
      goal: 'Baseline physiology assumption only — refined as we learn your trends.',
      fieldIds: ['biologicalSex'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 4,
      interactionPattern: 'chips',
    },
    {
      id: 'body',
      title: 'Height & weight',
      goal: 'Single screen, two numbers — anchors load and fueling.',
      fieldIds: ['heightCm', 'weightKg'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 12,
      interactionPattern: 'number inputs',
      helperCopy: 'Both go on one screen so it stays one step.',
    },
    {
      id: 'injury',
      title: 'Pain check',
      goal: 'Capture only current pain or injury information needed to protect early recommendations.',
      fieldIds: ['currentIssue', 'injuryLocations'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 10,
      interactionPattern: 'chips + body map',
      helperCopy: 'Only expands if the athlete reports a niggle or active injury.',
    },
    {
      id: 'coach',
      title: 'Coach code',
      goal: 'Optional 6-digit coach or academy code, skippable in one tap.',
      fieldIds: ['coachLockerCode'],
      mandatory: false,
      optional: true,
      conditional: false,
      expectedSeconds: 5,
      interactionPattern: 'text input',
      helperCopy: 'Skip if you do not have a code.',
    },
    {
      id: 'consent',
      title: 'Finish setup',
      goal: 'One consolidated agreement covers terms, privacy, medical disclaimer, AI use, and data processing.',
      fieldIds: ['platformConsent', 'guardianEmail'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 8,
      interactionPattern: 'single toggle (guardian email if minor)',
      helperCopy: 'The dashboard unlocks immediately after this.',
    },
  ],
}

export const athleteDailyFlow: FormFlowDefinition = {
  id: 'athlete-daily-quick',
  version: '2026.04.quick-check',
  userType: 'athlete',
  kind: 'daily',
  title: 'Athlete Check-In',
  description: 'A 10-second default check-in with deeper follow-ups only when signals look risky or ambiguous.',
  completionTargetSeconds: 10,
  fields: athleteDailyFields,
  defaultQuickSignalIds: ['energy', 'soreness', 'stress'],
  advancedSignalIds: ['sleepQuality', 'sleepDuration', 'painLocation', 'sessionCompletion', 'sessionRPE', 'sessionDuration'],
  steps: [
    {
      id: 'energy',
      title: 'Energy',
      goal: 'Measure central readiness with the fastest useful daily question.',
      fieldIds: ['energy'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'soreness',
      title: 'Body Feel',
      goal: 'Capture neuromuscular readiness and pain risk in one glance.',
      fieldIds: ['soreness'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'stress',
      title: 'Stress',
      goal: 'Capture mental and life load before training decisions are made.',
      fieldIds: ['stress'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'sleep',
      title: 'Why So Flat?',
      goal: 'Ask one short follow-up when energy and stress need more explanation.',
      fieldIds: ['sleepQuality', 'sleepDuration'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 5,
      interactionPattern: 'chips',
      helperCopy: 'Only shown on low-energy or high-stress days.',
    },
    {
      id: 'pain',
      title: 'Pain Protection',
      goal: 'Locate the issue only when soreness is high enough to change risk management.',
      fieldIds: ['painLocation'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 5,
      interactionPattern: 'body map',
    },
    {
      id: 'load',
      title: 'Training Load',
      goal: 'Capture yesterday load only when the system needs it for better confidence.',
      fieldIds: ['sessionCompletion', 'sessionRPE', 'sessionDuration'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 6,
      interactionPattern: 'chips + sliders',
    },
  ],
}

