import { coachOnboardingFields } from '@/forms/schemas/coachOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const coachOnboardingFlow: FormFlowDefinition = {
  id: 'coach-onboarding-fast',
  version: '2026.04.fast-start-6q',
  userType: 'coach',
  kind: 'onboarding',
  title: 'Coach Setup',
  description:
    'A 6-question setup that gets coaches to their squad dashboard fast. Coaches configure priorities and add more teams in-app afterwards.',
  completionTargetSeconds: 45,
  fields: coachOnboardingFields,
  steps: [
    {
      id: 'identity',
      title: 'Coach Identity',
      goal: 'Capture name and a working WhatsApp number for squad coordination.',
      fieldIds: ['fullName', 'mobileNumber'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 12,
      interactionPattern: 'text inputs',
    },
    {
      id: 'squad',
      title: 'Squad Setup',
      goal: 'Anchor sport and team name so the first dashboard is correctly configured.',
      fieldIds: ['sportCoached', 'teamName'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 12,
      interactionPattern: 'cards + text',
    },
    {
      id: 'structure',
      title: 'Coaching Context',
      goal: 'Understand the coaching level and squad size to size the dashboard.',
      fieldIds: ['coachingLevel', 'squadSize'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 10,
      interactionPattern: 'cards + numeric',
    },
    {
      id: 'consent',
      title: 'Confirm & Finish',
      goal: 'Single consolidated consent covering legal, medical, AI, and data handling.',
      fieldIds: ['platformConsent'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'single toggle',
    },
  ],
}
