import { individualDailyFields } from '@/forms/schemas/individualDaily'
import { individualOnboardingFields } from '@/forms/schemas/individualOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const individualOnboardingFlow: FormFlowDefinition = {
  id: 'individual-fitstart-fast',
  version: '2026.04.fast-start-10q',
  userType: 'individual',
  kind: 'onboarding',
  title: 'FitStart',
  description: 'Ten focused questions to anchor your first plan: who you are, what you want, and what you have.',
  completionTargetSeconds: 75,
  fields: individualOnboardingFields,
  steps: [
    {
      id: 'dob',
      title: 'Date of birth',
      goal: 'Anchor age-based recovery and progression.',
      fieldIds: ['dateOfBirth'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'date picker',
    },
    {
      id: 'gender',
      title: 'Sex / Gender',
      goal: 'Optional physiology anchor for early personalization.',
      fieldIds: ['gender'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 4,
      interactionPattern: 'chips',
    },
    {
      id: 'body-snapshot',
      title: 'Height & weight',
      goal: 'A quick body-size anchor on a single screen.',
      fieldIds: ['heightCm', 'weightKg'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'two number inputs',
    },
    {
      id: 'activity-level',
      title: 'Activity level',
      goal: 'A starting point before we learn your real patterns.',
      fieldIds: ['activityLevel'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'chips',
    },
    {
      id: 'primary-goal',
      title: 'Primary goal',
      goal: 'Focus the first journey around one outcome.',
      fieldIds: ['primaryGoal'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'goal cards',
    },
    {
      id: 'time-horizon',
      title: 'Time horizon',
      goal: 'Pace the plan to a horizon the user actually cares about.',
      fieldIds: ['timeHorizon'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 5,
      interactionPattern: 'chips',
    },
    {
      id: 'equipment',
      title: 'Equipment access',
      goal: 'Only ask for constraints that change what plan the user can follow.',
      fieldIds: ['equipmentAccess'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 6,
      interactionPattern: 'chips',
    },
    {
      id: 'workout-preference',
      title: 'Workout preference',
      goal: 'Match each session to a window the user can keep.',
      fieldIds: ['workoutPreference'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 5,
      interactionPattern: 'chips',
    },
    {
      id: 'limitations',
      title: 'Current limitations',
      goal: 'Capture only live limitations needed to avoid poor recommendations.',
      fieldIds: ['injuryStatus', 'limitationArea'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 8,
      interactionPattern: 'chips + body map',
    },
    {
      id: 'sleep-schedule',
      title: 'Sleep schedule',
      goal: 'Anchor recovery suggestions to the user’s real bedtime and wake time.',
      fieldIds: ['bedtime', 'wakeTime'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'two time inputs',
    },
    {
      id: 'consent',
      title: 'Consent',
      goal: 'Single consolidated consent before saving the plan.',
      fieldIds: ['consent'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 5,
      interactionPattern: 'single checkbox',
    },
  ],
}

export const individualDailyFlow: FormFlowDefinition = {
  id: 'individual-daily-quick',
  version: '2026.04.quick-check',
  userType: 'individual',
  kind: 'daily',
  title: 'Daily Pulse',
  description: 'Default check-in is three taps. Training details appear only when the user wants or needs them.',
  completionTargetSeconds: 10,
  fields: individualDailyFields,
  defaultQuickSignalIds: ['energy', 'stress', 'soreness'],
  advancedSignalIds: ['sleepQuality', 'sessionCompletion', 'trainingMinutes', 'sessionRPE', 'hydrationLiters'],
  steps: [
    {
      id: 'energy',
      title: 'Energy',
      goal: 'Get the strongest fast signal for how trainable today feels.',
      fieldIds: ['energy'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'stress',
      title: 'Stress',
      goal: 'Capture non-training load because it changes recovery and adherence.',
      fieldIds: ['stress'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'body',
      title: 'Body Feel',
      goal: 'Capture how physically ready the user feels right now.',
      fieldIds: ['soreness'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'sleep',
      title: 'Sleep Follow-Up',
      goal: 'Add sleep only on ambiguous or low-readiness days.',
      fieldIds: ['sleepQuality'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 4,
      interactionPattern: 'chips',
    },
    {
      id: 'training',
      title: 'Training Capture',
      goal: 'Capture actual training load only when the user wants the model to learn from today.',
      fieldIds: ['sessionCompletion', 'trainingMinutes', 'sessionRPE'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 6,
      interactionPattern: 'chips + sliders',
    },
  ],
}
